version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run:
          name: Update
          command: apt update
      - run:
          name: Install nodejs
          command: apt install nodejs npm -y && ln -s /usr/bin/nodejs /usr/bin/node
      - run:
          name: Install jasmine
          command: npm install -g jasmine
      - run:
          name: Test
          command: jasmine tests/*
